pipeline {
    agent { 
	docker {
            image 'maven:3-alpine'
        }
    }
    stages {	
        stage('Example 1') {
            steps {
                echo 'Hello, docker'
		echo ${WORKSPACE}
            }
        }
    }
}
