pipeline {
    agent { 
	docker 'maven:3-alpine' 
    	args '-v /root/.m2:/root/.m2'
    }
    stages {	
        stage('Example 1') {
            steps {
                echo 'Hello, docker'
		sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
