pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
	stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Example 1') {
            agent { docker 'demo-mysql' } 
            steps {
                echo 'Hello, Maven'
            }
        }
    }
}