server:
  port: 8080

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

---
spring:
  profiles: container
  application:
    name: customer-service
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://${MONGODB}}
