server:
  port: 8090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: userdb
    password: passdb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true

---  
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    database: MYSQL
    generate-ddl: true
