version: '3.0'

services:

  mysql-service:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orderdb
      - MYSQL_USER=userdb
      - MYSQL_PASSWORD=passdb

  order-service:
    image: carloselpapa10/order-service
    container_name: order-service
    depends_on:
      - mysql-service
    ports:
      - 5000:8090
    environment:
      - DATABASE_HOST=mysql-service
      - DATABASE_USER=userdb
      - DATABASE_PASSWORD=passdb
      - DATABASE_NAME=orderdb
      - DATABASE_PORT=3306
      - DATABASE_DRIVER=com.mysql.jdbc.Driver



