pipeline {
    agent none
    stages {
	stage('Maven Clean Package') {
		agent {
			docker { image 'maven:3-alpine' }
	      	}
	     	steps {
			sh 'mvn -f "4.Jenkins/pom.xml" -B -DskipTests clean package docker:build'
	      	}
	} 
    }
}
