pipeline {
    agent none
    tools { 
        maven 'maven-3' 
    }
    stages {
	    stage('Test') {
		    agent any
		    steps {
			sh 'docker stop mysql'  
			sh 'docker rm mysql'				    
		    }		
	    }	
	    post { 
        failure { 
            echo 'error controlled'
        }
    }
	stage('Mysql Container') {
	      agent any
	      steps {
		sh 'docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=orderdb -e MYSQL_USER=userdb -e MYSQL_PASSWORD=passdb mysql:latest'
	      }
	}
    }

}
