version: '3.0'

services:

  eureka:
    image: springcloud/eureka
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

  admin-service:
    build: ./admin    
    depends_on:
      - eureka
    container_name: admin
    volumes:
      - ./build/libs:/app
    ports:
      - 5000:8093
    networks:
      - "discovery"

  config:
    image: springcloud/configserver
    container_name: config
    depends_on:
      - eureka
    ports:
      - "8888:8888"
    networks:
      - "discovery"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-service:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  test-producer-service:
    build: ./test-producer
    container_name: test-producer-service
    volumes:
      - ./build/libs:/app
    ports:
      - 5001:8070
    depends_on:
      - admin-service
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - CONFIG_SERVER_URI=http://config:8888

  zuul-gateway:
    build: ./zuul-gateway
    container_name: zuul-gateway-service
    volumes:
      - ./build/libs:/app
    ports:
      - 5002:8079
    depends_on:
      - eureka
      - test-producer-service
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - CONFIG_SERVER_URI=http://config:8888

  test-consumer-service:
    build: ./test-consumer
    container_name: test-consumer-service
    volumes:
      - ./build/libs:/app
    ports:
      - 5003:8091
    depends_on:
      - zuul-gateway
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - CONFIG_SERVER_URI=http://config:8888

networks:
  discovery: